apiVersion: v1
kind: Service
metadata:
  name: redis-proxy
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redis-proxy
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
