name: Publish Helm Chart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package-and-publish:
    name: Package and Publish Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: |
          helm package deployments/helm --destination ./packages

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          charts_dir: ./deployments
          target_dir: ./charts
